[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow",
]

[tool.isort]
profile = "black"
line_length = 79
honor_noqa = true
src_paths = ["botocore", "tests"]

[tool.black]
line-length = 79
skip_string_normalization = true

[tool.codespell]
skip = """\
    ./botocore/data,\
    ./botocore/cacert.pem,\
    ./botocore/vendored,\
    ./tests/functional/data,\
    ./tests/functional/endpoint-rules,\
    ./tests/functional/csm/data,\
    ./tests/functional/models,\
    ./CHANGELOG.rst,\
    ./docs/source/_static/shortbreadv1.js,\
    ./tests/unit/data/endpoints/valid-rules,\
    ./.git,\
    ./botocore.egg-info,\
    ./.pytest_cache,\
"""
exclude-file=".codespellignorelines"