name: Run Zip tests

on:
  push:
  pull_request:
    branches-ignore: [master]

jobs:
  zip:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11-dev']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          python scripts/ci/install
      - name: Set path seperator for windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "PATH_SEPERATOR=\" >> $GITHUB_ENV
      - name: Set path seperator for ubuntu/mac
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          echo "PATH_SEPERATOR=/" >> $GITHUB_ENV
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}${{ env.PATH_SEPERATOR }}botocore.zip
        run: |
          python -m zipfile -c botocore.zip botocore/
          python scripts/ci/run-zip-tests --with-cov --with-xdist --append-import
          rm botocore.zip
